### ISSUE TITLE
Error with elastic registration/shift registration in google cloud function

### ISSUE THREAD

**Issue by jrash33** [GAA-UAM/scikit-fda#300]
Please help! I am trying to implement this awesome library in a google cloud function but am getting an Assertion Error.:

Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 21, in hello_world fd_registered = shift_registration.fit_transform(fd_us) File "/env/local/lib/python3.7/site-packages/skfda/preprocessing/registration/_shift_registration.py", line 292, in fit_transform self.deltas_, self.template_ = self._compute_deltas(X, self.template) File "/env/local/lib/python3.7/site-packages/skfda/preprocessing/registration/_shift_registration.py", line 187, in _compute_deltas fd_deriv = fd.derivative(order=1) File "/env/local/lib/python3.7/site-packages/skfda/representation/grid.py", line 428, in derivative zip(self.sample_points, order_list))]) File "/env/local/lib/python3.7/site-packages/findiff/operators.py", line 77, in __init__ self.pds = self._eval_args(args, kwargs) File "/env/local/lib/python3.7/site-packages/findiff/operators.py", line 147, in _eval_args pds = Diff(axis, order) File "/env/local/lib/python3.7/site-packages/findiff/diff.py", line 264, in __init__ assert isinstance(order, int) AssertionError

Getting this fda function to work properly is critical to my app and don't know what to do. Currently, I am trying to go back to previous versions and hoping that makes a difference but thought I would try the channel. I am just trying a simple code snippet given from the provided notebook and it errors out on the elastic_registration.fit_transform(fd) function:

fd = make_multimodal_samples(n_modes=2, stop=4, random_state=1)
elastic_registration = ElasticRegistration()
fd_align = elastic_registration.fit_transform(fd)

**Comment by vnmabus** [comment]
This error is caused by https://github.com/maroba/findiff/issues/32#issuecomment-752016899. I think @maroba is going to fix it. If you need a solution right now, try installing `findiff==0.8.3`.

**Comment by jrash33** [comment]
@vnmabus thanks so much - findiff fixed it

**Comment by maroba** [comment]
Version 0.8.7 of findiff is now available which has fixed this issue.
