### ISSUE TITLE
First import error `FisherRaoElasticRegistration`

### ISSUE THREAD

**Issue by ego-thales** [GAA-UAM/scikit-fda#527]
Hi,

I just wanted to report the following issue. When trying to import `FisherRaoElasticRegistration` from a clean session, I get an error. Upon retrying, it then works.
```pycon
>>> from skfda.preprocessing.registration import FisherRaoElasticRegistration  # Doesn't work
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File ".../python3.10/site-packages/lazy_loader/__init__.py", line 76, in __getattr__
    submod = importlib.import_module(submod_path)
  File ".../python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File ".../python3.10/site-packages/skfda/preprocessing/registration/_fisher_rao.py", line 11, in <module>
    from ...exploratory.stats import fisher_rao_karcher_mean
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File ".../python3.10/site-packages/lazy_loader/__init__.py", line 76, in __getattr__
    submod = importlib.import_module(submod_path)
  File ".../python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File ".../python3.10/site-packages/skfda/exploratory/stats/_fisher_rao.py", line 7, in <module>
    from fdasrsf.utility_functions import optimum_reparam
  File ".../python3.10/site-packages/fdasrsf/__init__.py", line 44, in <module>
    from .umap_metric import efda_distance, efda_distance_curve
  File ".../python3.10/site-packages/fdasrsf/umap_metric.py", line 9, in <module>
    import numba
  File ".../python3/dist-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File ".../python3/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File ".../python3/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
>>> from skfda.preprocessing.registration import FisherRaoElasticRegistration  # Now works fine
>>> 
```

**Version information**
 - OS: Ubuntu 20.04
 - Python version: 3.10.6
 - scikit-fda version: 0.8.1

Cheers!

**Comment by vnmabus** [comment]
I think it is a problem with Numba. Check if your version of Numba and NumPy are compatible, as Numba is not always able to catch up with recent NumPy versions.

**Comment by vnmabus** [comment]
@ego-thales I did never hear back. Can this issue be closed?

**Comment by ego-thales** [comment]
Hey @vnmabus!

For good measure, I just tried from a fresh project and got an _a priori_ completely different problem.
```pycon
$ uv run python
Python 3.13.1 (main, Dec 19 2024, 14:32:25) [Clang 18.1.8 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from skfda.preprocessing.registration import FisherRaoElasticRegistration
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from skfda.preprocessing.registration import FisherRaoElasticRegistration
  File "[...]/workspace/tmp/.venv/lib/python3.13/site-packages/skfda/preprocessing/registration/__init__.py", line 10, in <module>
    from ..._utils import (
    ...<2 lines>...
    )
ImportError: cannot import name 'invert_warping' from 'skfda._utils' ([...]/workspace/tmp/.venv/lib/python3.13/site-packages/skfda/_utils/__init__.py)
>>> 
```

### Environment

System: Ubuntu 20.04
Env manager: `uv 0.6.6`
Dependencies:
```
$ uv tree
Resolved 39 packages in 0.43ms
tmp v0.1.0
└── scikit-fda v0.9.1
    ├── dcor v0.6
    │   ├── joblib v1.4.2
    │   ├── numba v0.61.0
    │   │   ├── llvmlite v0.44.0
    │   │   └── numpy v2.1.3
    │   ├── numpy v2.1.3
    │   └── scipy v1.15.2
    │       └── numpy v2.1.3
    ├── fdasrsf v2.6.1
    │   ├── cffi v1.17.1
    │   │   └── pycparser v2.22
    │   ├── cython v3.0.12
    │   ├── joblib v1.4.2
    │   ├── matplotlib v3.10.1
    │   │   ├── contourpy v1.3.1
    │   │   │   └── numpy v2.1.3
    │   │   ├── cycler v0.12.1
    │   │   ├── fonttools v4.56.0
    │   │   ├── kiwisolver v1.4.8
    │   │   ├── numpy v2.1.3
    │   │   ├── packaging v24.2
    │   │   ├── pillow v11.1.0
    │   │   ├── pyparsing v3.2.2
    │   │   └── python-dateutil v2.9.0.post0
    │   │       └── six v1.17.0
    │   ├── numba v0.61.0 (*)
    │   ├── numpy v2.1.3
    │   ├── patsy v1.0.1
    │   │   └── numpy v2.1.3
    │   ├── pyparsing v3.2.2
    │   ├── scipy v1.15.2 (*)
    │   ├── six v1.17.0
    │   └── tqdm v4.67.1
    ├── findiff v0.12.1
    │   ├── numpy v2.1.3
    │   ├── scipy v1.15.2 (*)
    │   └── sympy v1.13.3
    │       └── mpmath v1.3.0
    ├── lazy-loader v0.4
    │   └── packaging v24.2
    ├── matplotlib v3.10.1 (*)
    ├── multimethod v2.0
    ├── numpy v2.1.3
    ├── pandas v2.2.3
    │   ├── numpy v2.1.3
    │   ├── python-dateutil v2.9.0.post0 (*)
    │   ├── pytz v2025.1
    │   └── tzdata v2025.2
    ├── rdata v0.11.2
    │   ├── numpy v2.1.3
    │   ├── pandas v2.2.3 (*)
    │   ├── typing-extensions v4.12.2
    │   └── xarray v2025.3.0
    │       ├── numpy v2.1.3
    │       ├── packaging v24.2
    │       └── pandas v2.2.3 (*)
    ├── scikit-datasets[cran] v0.2.4
    │   ├── numpy v2.1.3
    │   ├── scikit-learn v1.6.1
    │   │   ├── joblib v1.4.2
    │   │   ├── numpy v2.1.3
    │   │   ├── scipy v1.15.2 (*)
    │   │   └── threadpoolctl v3.6.0
    │   ├── scipy v1.15.2 (*)
    │   └── rdata v0.11.2 (extra: cran) (*)
    ├── scikit-learn v1.6.1 (*)
    ├── scipy v1.15.2 (*)
    └── typing-extensions v4.12.2
(*) Package tree already displayed
```

So I let you decide, but it might be better to open a new issue first, and upon the new issue being fixed, checking if the original one is fixed too?

All the best!

**Comment by vnmabus** [comment]
Are you using the latest release or the develop version? Because the latest release is very outdated and does not support a lot of newer versions of packages (I plan to do a release as soon as I merge #618, so hopefully in the next few weeks).

Sorry, because I had a lot of personal issues that left me with very little time for my Github projects. Hopefully I can improve things here now.

**Comment by ego-thales** [comment]
It was the latest release! It works like a charm with`scikit-fda v0.9.2.dev0` :)

So I guess it's all good, I'll let you close it if you ever want to link a reference to commit or do something else.

> Sorry, because I had a lot of personal issues that left me with very little time for my Github projects. Hopefully I can improve things here now.

As I think you once told me: don't apologize for not having the time to work for free on an open-source project. It still applies to the main dev ;)

Cheers!

**Comment by vnmabus** [comment]
Thanks for checking! I will close the issue then.
