### ISSUE TITLE
TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by buddih09** [GAA-UAM/scikit-fda#604]
### Bug description summary

When I try to import skfda, the import fails with TypeError: 'ABCMeta' object is not subscriptable

### Code to reproduce the bug

```Python
from skfda.ml.clustering import FuzzyCMeans
from sklearn.datasets import load_iris

if __name__ == '__main__':
    # Load iris data from scikit-learn as a pandas DataFrame
    iris = load_iris()
    df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
    # Shape of the dataset (n_features, n_samples)
    df = df.to_numpy().T

    fcm = FuzzyCMeans(random_state=0)
    fcm.fit(df)
```

### Expected result

The import should work

### Actual result

Import fails 

### Traceback (if an exception is raised)

```Python
Traceback (most recent call last):
  File "C:\Users\buddi\PycharmProjects\cs-choice-model\test\clustering.py", line 1, in <module>
    from skfda.ml.clustering import FuzzyCMeans
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "C:\Conda\envs\fuzzy\lib\site-packages\lazy_loader\__init__.py", line 77, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Conda\envs\fuzzy\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Conda\envs\fuzzy\lib\site-packages\skfda\ml\clustering\_kmeans.py", line 17, in <module>
    from ...misc.metrics import PairwiseMetric, l2_distance
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "C:\Conda\envs\fuzzy\lib\site-packages\lazy_loader\__init__.py", line 77, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Conda\envs\fuzzy\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Conda\envs\fuzzy\lib\site-packages\skfda\misc\metrics\_utils.py", line 4, in <module>
    import multimethod
  File "C:\Conda\envs\fuzzy\lib\site-packages\multimethod\__init__.py", line 34, in <module>
    class subtype(abc.ABCMeta):
  File "C:\Conda\envs\fuzzy\lib\site-packages\multimethod\__init__.py", line 126, in subtype
    def origins(self) -> Iterator[type]:
TypeError: 'ABCMeta' object is not subscriptable
```

### Software versions

version 0.9
windows 10

**Comment by vnmabus** [comment]
Sorry for not answering earlier. I couldn't reproduce the error in my computer. I notice that the exception is raised in the [multimethod package](https://github.com/coady/multimethod/), in a line that seems to have been changed in latter versions. I suggest to try with another version of the multimethod package, and report back if it works or not.

**Comment by vnmabus** [comment]
As I was unable to reproduce, and there is no answer from the issuer, I will assume that this was fixed when updating `multimethod`. Please reopen if that is not the case.
